# Script for populating the database. You can run it as:
#
#     mix run priv/repo/seeds.exs
#
# Inside the script, you can read and write to any of your
# repositories directly:
#
#     Fallout_4Tracker.Repo.insert!(%Fallout_4Tracker.SomeModel{})
#
# We recommend using the bang functions (`insert!`, `update!`
# and so on) as they will fail if something goes wrong.

alias Fallout_4Tracker.Repo
alias Fallout_4Tracker.Quest

Repo.insert!(%Quest{name: "War Never Changes", category: "main", status: "not_started"})
Repo.insert!(%Quest{name: "Out of Time", category: "main", status: "not_started"})
Repo.insert!(%Quest{name: "Jewel of the Commonwealth", category: "main", status: "not_started"})
Repo.insert!(%Quest{name: "Unlikely Valentine", category: "main", status: "not_started"})
Repo.insert!(%Quest{name: "Getting a Clue", category: "main", status: "not_started"})
Repo.insert!(%Quest{name: "Reunions", category: "main", status: "not_started"})
Repo.insert!(%Quest{name: "Dangerous Minds", category: "main", status: "not_started"})
Repo.insert!(%Quest{name: "The Glowing Sea", category: "main", status: "not_started"})
Repo.insert!(%Quest{name: "Hunter/Hunted", category: "main", status: "not_started"})
Repo.insert!(%Quest{name: "The Molecular Level", category: "main", status: "not_started"})
Repo.insert!(%Quest{name: "Institutionalized", category: "main", status: "not_started"})

Repo.insert!(%Quest{name: "Cambridge Polymer Labs", category: "side", status: "not_started"})
Repo.insert!(%Quest{name: "Confidence Man", category: "side", status: "not_started"})
Repo.insert!(%Quest{name: "Curtain Call", category: "side", status: "not_started"})
Repo.insert!(%Quest{name: "Dependency", category: "side", status: "not_started"})
Repo.insert!(%Quest{name: "Diamond City Blues", category: "side", status: "not_started"})
Repo.insert!(%Quest{name: "Emogene Takes a Lover", category: "side", status: "not_started"})
Repo.insert!(%Quest{name: "Here Kitty, Kitty", category: "side", status: "not_started"})
Repo.insert!(%Quest{name: "Here There Be Monsters", category: "side", status: "not_started"})
Repo.insert!(%Quest{name: "Hole in the Wall", category: "side", status: "not_started"})
Repo.insert!(%Quest{name: "Human Error", category: "side", status: "not_started"})
Repo.insert!(%Quest{name: "In Sheep's Clothing", category: "side", status: "not_started"})
Repo.insert!(%Quest{name: "Kid in a Fridge", category: "side", status: "not_started"})
Repo.insert!(%Quest{name: "Last Voyage of the U.S.S. Constitution", category: "side", status: "not_started"})
Repo.insert!(%Quest{name: "Mystery Meat", category: "side", status: "not_started"})
Repo.insert!(%Quest{name: "Order Up", category: "side", status: "not_started"})
Repo.insert!(%Quest{name: "Out in Left Field", category: "side", status: "not_started"})
Repo.insert!(%Quest{name: "Out of the Fire", category: "side", status: "not_started"})
Repo.insert!(%Quest{name: "Painting the Town", category: "side", status: "not_started"})
Repo.insert!(%Quest{name: "Pickman's Gift", category: "side", status: "not_started"})
Repo.insert!(%Quest{name: "Public Knowledge", category: "side", status: "not_started"})
Repo.insert!(%Quest{name: "Pull the Plug", category: "side", status: "not_started"})
Repo.insert!(%Quest{name: "Short Stories", category: "side", status: "not_started"})
Repo.insert!(%Quest{name: "Special Delivery", category: "side", status: "not_started"})
Repo.insert!(%Quest{name: "Story of the Century", category: "side", status: "not_started"})
Repo.insert!(%Quest{name: "The Big Dig", category: "side", status: "not_started"})
Repo.insert!(%Quest{name: "The Devil's Due", category: "side", status: "not_started"})
Repo.insert!(%Quest{name: "The Disappearing Act", category: "side", status: "not_started"})
Repo.insert!(%Quest{name: "The Gilded Grasshopper", category: "side", status: "not_started"})
Repo.insert!(%Quest{name: "The Marowski Heist", category: "side", status: "not_started"})
Repo.insert!(%Quest{name: "The Memory Den", category: "side", status: "not_started"})
Repo.insert!(%Quest{name: "The Secret of Cabot House", category: "side", status: "not_started"})
Repo.insert!(%Quest{name: "The Silver Shroud", category: "side", status: "not_started"})
Repo.insert!(%Quest{name: "Trouble Brewin'", category: "side", status: "not_started"})
Repo.insert!(%Quest{name: "Troubled Waters", category: "side", status: "not_started"})
Repo.insert!(%Quest{name: "Vault 75", category: "side", status: "not_started"})
Repo.insert!(%Quest{name: "Vault 81", category: "side", status: "not_started"})

Repo.insert!(%Quest{name: "Benign Intervention", category: "companion", status: "not_started"})
Repo.insert!(%Quest{name: "Emergent Behavior", category: "companion", status: "not_started"})
Repo.insert!(%Quest{name: "Long Road Ahead", category: "companion", status: "not_started"})
Repo.insert!(%Quest{name: "Long Time Coming", category: "companion", status: "not_started"})

Repo.insert!(%Quest{name: "Art Appreciation", category: "misc", status: "not_started"})
Repo.insert!(%Quest{name: "Atom Cats", category: "misc", status: "not_started"})
Repo.insert!(%Quest{name: "Botany Class", category: "misc", status: "not_started"})
Repo.insert!(%Quest{name: "The Cleaner", category: "misc", status: "not_started"})
Repo.insert!(%Quest{name: "The Combat Zone", category: "misc", status: "not_started"})
Repo.insert!(%Quest{name: "Detective Case Files", category: "misc", status: "not_started"})
Repo.insert!(%Quest{name: "Diamond City's Most Wanted", category: "misc", status: "not_started"})
Repo.insert!(%Quest{name: "Fallen Hero", category: "misc", status: "not_started"})
Repo.insert!(%Quest{name: "Find the Treasures of Jamaica Plain", category: "misc", status: "not_started"})
Repo.insert!(%Quest{name: "Fly Fishing", category: "misc", status: "not_started"})
Repo.insert!(%Quest{name: "Giddyup 'n Go", category: "misc", status: "not_started"})
Repo.insert!(%Quest{name: "Greet the Dog", category: "misc", status: "not_started"})
Repo.insert!(%Quest{name: "Gun Run", category: "misc", status: "not_started"})
Repo.insert!(%Quest{name: "Hazardous Material", category: "misc", status: "not_started"})
Repo.insert!(%Quest{name: "MacCready for Action", category: "misc", status: "not_started"})
Repo.insert!(%Quest{name: "Meet Ness at the Crash Site", category: "misc", status: "not_started"})
Repo.insert!(%Quest{name: "Nuka Cola Needs", category: "misc", status: "not_started"})
Repo.insert!(%Quest{name: "Pool Cleaning", category: "misc", status: "not_started"})
Repo.insert!(%Quest{name: "Prep School", category: "misc", status: "not_started"})
Repo.insert!(%Quest{name: "Report to the Director of the General Atomics Galleria", category: "misc", status: "not_started"})
Repo.insert!(%Quest{name: "Search for caps in (location)", category: "misc", status: "not_started"})
Repo.insert!(%Quest{name: "Look for the stash of chems in (location)", category: "misc", status: "not_started"})
Repo.insert!(%Quest{name: "Find the (weapon) in (location)", category: "misc", status: "not_started"})
Repo.insert!(%Quest{name: "Search for scrap in (location)", category: "misc", status: "not_started"})
Repo.insert!(%Quest{name: "Search for tech in (location)﻿", category: "misc", status: "not_started"})
Repo.insert!(%Quest{name: "Traffic Jam", category: "misc", status: "not_started"})
Repo.insert!(%Quest{name: "Vault 81 Tour", category: "misc", status: "not_started"})
Repo.insert!(%Quest{name: "Virgil's Cure", category: "misc", status: "not_started"})
Repo.insert!(%Quest{name: "Investigate the Museum of Witchcraft", category: "misc", status: "not_started"})
Repo.insert!(%Quest{name: "Get the Latest Issue of Publick Occurrences", category: "misc", status: "not_started"})

Repo.insert!(%Quest{name: "A Pillar of the Community", category: "unmarked", status: "not_started"})
Repo.insert!(%Quest{name: "Bill Sutton", category: "unmarked", status: "not_started"})
Repo.insert!(%Quest{name: "Brother Against Brother", category: "unmarked", status: "not_started"})
Repo.insert!(%Quest{name: "Familiar Faces", category: "unmarked", status: "not_started"})
Repo.insert!(%Quest{name: "Fertilizer Woman", category: "unmarked", status: "not_started"})
Repo.insert!(%Quest{name: "Holly", category: "unmarked", status: "not_started"})
Repo.insert!(%Quest{name: "Lucy Abernathy", category: "unmarked", status: "not_started"})
Repo.insert!(%Quest{name: "Maintenance Man", category: "unmarked", status: "not_started"})
Repo.insert!(%Quest{name: "Quality Assurance", category: "unmarked", status: "not_started"})
Repo.insert!(%Quest{name: "Supervisor Brown", category: "unmarked", status: "not_started"})
Repo.insert!(%Quest{name: "Supervisor Greene", category: "unmarked", status: "not_started"})
Repo.insert!(%Quest{name: "Wedding Day", category: "unmarked", status: "not_started"})

Repo.insert!(%Quest{name: "Reveille", category: "bos_main", status: "not_started"})
Repo.insert!(%Quest{name: "Fire Support", category: "bos_main", status: "not_started"})
Repo.insert!(%Quest{name: "Call to Arms", category: "bos_main", status: "not_started"})
Repo.insert!(%Quest{name: "Semper Invicta", category: "bos_main", status: "not_started"})
Repo.insert!(%Quest{name: "Shadow of Steel", category: "bos_main", status: "not_started"})
Repo.insert!(%Quest{name: "Tour of Duty", category: "bos_main", status: "not_started"})
Repo.insert!(%Quest{name: "Show No Mercy", category: "bos_main", status: "not_started"})
Repo.insert!(%Quest{name: "From Within", category: "bos_main", status: "not_started"})
Repo.insert!(%Quest{name: "Outside the Wire", category: "bos_main", status: "not_started"})
Repo.insert!(%Quest{name: "Liberty Reprimed", category: "bos_main", status: "not_started"})
Repo.insert!(%Quest{name: "Blind Betrayal", category: "bos_main", status: "not_started"})
Repo.insert!(%Quest{name: "Tactical Thinking", category: "bos_main", status: "not_started"})
Repo.insert!(%Quest{name: "Spoils of War", category: "bos_main", status: "not_started"})
Repo.insert!(%Quest{name: "Ad Victoriam", category: "bos_main", status: "not_started"})
Repo.insert!(%Quest{name: "The Nuclear Option", category: "bos_main", status: "not_started"})
Repo.insert!(%Quest{name: "A New Dawn", category: "bos_main", status: "not_started"})
Repo.insert!(%Quest{name: "A Loose End", category: "bos_side", status: "not_started"})
Repo.insert!(%Quest{name: "Duty or Dishonor", category: "bos_side", status: "not_started"})
Repo.insert!(%Quest{name: "The Lost Patrol", category: "bos_side", status: "not_started"})
Repo.insert!(%Quest{name: "Cleansing the Commonwealth", category: "bos_radiant", status: "not_started"})
Repo.insert!(%Quest{name: "Feeding the Troops", category: "bos_radiant", status: "not_started"})
Repo.insert!(%Quest{name: "Leading by Example", category: "bos_radiant", status: "not_started"})
Repo.insert!(%Quest{name: "Learning Curve", category: "bos_radiant", status: "not_started"})
Repo.insert!(%Quest{name: "Quartermastery", category: "bos_radiant", status: "not_started"})
Repo.insert!(%Quest{name: "Blood Bank", category: "bos_repeatable", status: "not_started"})
Repo.insert!(%Quest{name: "Getting Technical", category: "bos_repeatable", status: "not_started"})
Repo.insert!(%Quest{name: "Reactor Coolant", category: "bos_repeatable", status: "not_started"})

Repo.insert!(%Quest{name: "When Freedom Calls", category: "minutemen_main", status: "not_started"})
Repo.insert!(%Quest{name: "Sanctuary", category: "minutemen_main", status: "not_started"})
Repo.insert!(%Quest{name: "The First Step", category: "minutemen_main", status: "not_started"})
Repo.insert!(%Quest{name: "Taking Independence", category: "minutemen_main", status: "not_started"})
Repo.insert!(%Quest{name: "Old Guns", category: "minutemen_main", status: "not_started"})
Repo.insert!(%Quest{name: "Inside Job", category: "minutemen_main", status: "not_started"})
Repo.insert!(%Quest{name: "Form Ranks", category: "minutemen_main", status: "not_started"})
Repo.insert!(%Quest{name: "Defend the Castle", category: "minutemen_main", status: "not_started"})
Repo.insert!(%Quest{name: "The Nuclear Option", category: "minutemen_main", status: "not_started"})
Repo.insert!(%Quest{name: "With Our Powers Combined", category: "minutemen_main", status: "not_started"})

Repo.insert!(%Quest{name: "Returning the Favor", category: "minutemen_side", status: "not_started"})
Repo.insert!(%Quest{name: "The Sight", category: "minutemen_side", status: "not_started"})

Repo.insert!(%Quest{name: "Clearing the Way", category: "minutemen_radiant", status: "not_started"})
Repo.insert!(%Quest{name: "Ghoul Problem", category: "minutemen_radiant", status: "not_started"})
Repo.insert!(%Quest{name: "Greenskins", category: "minutemen_radiant", status: "not_started"})
Repo.insert!(%Quest{name: "Kidnapping", category: "minutemen_radiant", status: "not_started"})
Repo.insert!(%Quest{name: "Raider Troubles", category: "minutemen_radiant", status: "not_started"})
Repo.insert!(%Quest{name: "Resettle Refugees", category: "minutemen_radiant", status: "not_started"})
Repo.insert!(%Quest{name: "Rogue Courser", category: "minutemen_radiant", status: "not_started"})
Repo.insert!(%Quest{name: "Stop the Raiding", category: "minutemen_radiant", status: "not_started"})
Repo.insert!(%Quest{name: "Taking Point", category: "minutemen_radiant", status: "not_started"})
Repo.insert!(%Quest{name: "Help Defend", category: "minutemen_radiant", status: "not_started"})
Repo.insert!(%Quest{name: "Defent the Artillery", category: "minutemen_radiant", status: "not_started"})
Repo.insert!(%Quest{name: "Suspected Synth", category: "minutemen_radiant", status: "not_started"})

Repo.insert!(%Quest{name: "Road to Freedom", category: "railroad_main", status: "not_started"})
Repo.insert!(%Quest{name: "Tradecraft", category: "railroad_main", status: "not_started"})
Repo.insert!(%Quest{name: "Underground Undercover", category: "railroad_main", status: "not_started"})
Repo.insert!(%Quest{name: "Precipice of War", category: "railroad_main", status: "not_started"})
Repo.insert!(%Quest{name: "Rockets' Red Glare", category: "railroad_main", status: "not_started"})
Repo.insert!(%Quest{name: "The Nuclear Option", category: "railroad_main", status: "not_started"})

Repo.insert!(%Quest{name: "Boston After Dark", category: "railroad_side", status: "not_started"})
Repo.insert!(%Quest{name: "Mercer Safehouse", category: "railroad_side", status: "not_started"})
Repo.insert!(%Quest{name: "Burning Cover", category: "railroad_side", status: "not_started"})
Repo.insert!(%Quest{name: "Butcher's Bill", category: "railroad_side", status: "not_started"})
Repo.insert!(%Quest{name: "Butcher's Bill 2", category: "railroad_side", status: "not_started"})
Repo.insert!(%Quest{name: "Memory Interrupted", category: "railroad_side", status: "not_started"})
Repo.insert!(%Quest{name: "Operation Ticonderoga", category: "railroad_side", status: "not_started"})

Repo.insert!(%Quest{name: "A Clean Equation", category: "railroad_radiant", status: "not_started"})
Repo.insert!(%Quest{name: "Concierge", category: "railroad_radiant", status: "not_started"})
Repo.insert!(%Quest{name: "High Ground", category: "railroad_radiant", status: "not_started"})
Repo.insert!(%Quest{name: "Jackpot", category: "railroad_radiant", status: "not_started"})
Repo.insert!(%Quest{name: "Lost Soul", category: "railroad_radiant", status: "not_started"})
Repo.insert!(%Quest{name: "Randolph Safehouse", category: "railroad_radiant", status: "not_started"})
Repo.insert!(%Quest{name: "To the Mattresses", category: "railroad_radiant", status: "not_started"})
Repo.insert!(%Quest{name: "Variable Removal", category: "railroad_radiant", status: "not_started"})
Repo.insert!(%Quest{name: "Weathervane", category: "railroad_radiant", status: "not_started"})

Repo.insert!(%Quest{name: "Synth Retention", category: "institute_main", status: "not_started"})
Repo.insert!(%Quest{name: "The Battle of Bunker Hill", category: "institute_main", status: "not_started"})
Repo.insert!(%Quest{name: "Mankind-Redefined", category: "institute_main", status: "not_started"})
Repo.insert!(%Quest{name: "Mass Fusion", category: "institute_main", status: "not_started"})
Repo.insert!(%Quest{name: "Pinned", category: "institute_main", status: "not_started"})
Repo.insert!(%Quest{name: "Powering Up", category: "institute_main", status: "not_started"})
Repo.insert!(%Quest{name: "End of the Line", category: "institute_main", status: "not_started"})
Repo.insert!(%Quest{name: "Airship Down", category: "institute_main", status: "not_started"})
Repo.insert!(%Quest{name: "Nuclear Family", category: "institute_main", status: "not_started"})

Repo.insert!(%Quest{name: "A House Divided", category: "institute_side", status: "not_started"})
Repo.insert!(%Quest{name: "Banished from the Institute", category: "institute_side", status: "not_started"})
Repo.insert!(%Quest{name: "Building a Better Crop", category: "institute_side", status: "not_started"})
Repo.insert!(%Quest{name: "Plugging a Leak", category: "institute_side", status: "not_started"})
Repo.insert!(%Quest{name: "Political Leanings", category: "institute_side", status: "not_started"})

Repo.insert!(%Quest{name: "Appropriation", category: "institute_radiant", status: "not_started"})
Repo.insert!(%Quest{name: "Hypothesis", category: "institute_radiant", status: "not_started"})
Repo.insert!(%Quest{name: "Pest Control", category: "institute_radiant", status: "not_started"})
Repo.insert!(%Quest{name: "Reclamation", category: "institute_radiant", status: "not_started"})

Repo.insert!(%Quest{name: "Mechanical Menace", category: "automatron_main", status: "not_started"})
Repo.insert!(%Quest{name: "A New Threat", category: "automatron_main", status: "not_started"})
Repo.insert!(%Quest{name: "Headhunting", category: "automatron_main", status: "not_started"})
Repo.insert!(%Quest{name: "Restoring Order", category: "automatron_main", status: "not_started"})
Repo.insert!(%Quest{name: "Rogue Robot", category: "automatron_side", status: "not_started"})

